name: CI - Springboot
run-name: springboot build - ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
